### ISSUE TITLE
Probandolo

### ISSUE THREAD

**Issue by RonaldChonillo** [jordiicabrera/FirmaElectronica#1]
Voy a probarlo, muchas gracias.

**Comment by RonaldChonillo** [comment]
No funciona

**Comment by jordiicabrera** [comment]
@RonaldChonillo estimado la firma funciona para el ambiente de producción. Lamentablemente en el ambiente de pruebas el SRI esta cambiando la forma del firmado y es por esta razón que no funciona con el ambiente de pruebas.

**Comment by RonaldChonillo** [comment]
> @RonaldChonillo estimado la firma funciona para el ambiente de producción. Lamentablemente en el ambiente de pruebas el SRI esta cambiando la forma del firmado y es por esta razón que no funciona con el ambiente de pruebas.

Muchas gracias!
